### ISSUE TITLE
Runs abnormally, no styles

### ISSUE THREAD

**Issue by sunjiahe-hub** [euxhenh/cellar#6]
Hello,
         whether it is running locally with docker or running on the web, it is found that the website is not loaded correctly, and some styles are not displayed. What do I need to do to use it normally?
![image](https://user-images.githubusercontent.com/69581197/177674390-448c2c6a-ebad-4365-a62e-4afc59a3bc65.png)

**Comment by euxhenh** [comment]
Hi, Can you post some details about the OS and the browser you are using?

**Comment by sunjiahe-hub** [comment]
thank you for your reply！
Operating system: I use the web version and the docker version on Windows 10 and Ubuntu18.04 respectively, and they are not loaded properly
Browser: Google Chrome

**Comment by euxhenh** [comment]
Hi,
Are you behind a proxy or perhaps somehow disabled networking for the container? Cellar requires internet connection to download some stylesheets, so that could be the problem.

**Comment by euxhenh** [comment]
That's great! I'll mark this issue as closed for now. If you have any leads as to what is causing the docker problem, we can reopen it as needed.
